version: 0.1

phases:
  install:
    commands:
      - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
      - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      - apt-get update
      - apt-get install openjdk-8-jre icedtea-8-plugin
      - apt-get install sbt -y

  build:
    commands:
      - sbt docker:publishLocal
      - docker tag $ECR_TAG $ECR_REPOSITORY:1.0
      - docker push $ECR_REPOSITORY