version: 0.1

phases:
  install:
    commands:
      - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update
      - apt-get install openjdk-11-jre -y
      - apt-get install sbt -y

  build:
    commands:
      - sbt docker:publishLocal
      - docker tag $ECR_TAG $ECR_REPOSITORY:1.0
      - docker push $ECR_REPOSITORY